name: apiraiser
description: Dart package for accessing Apiraiser, a headless CMS which provides easy-to-use backend for various kinds of applications like E-commerce, blogs, CMS etc.
version: 0.1.6
homepage: https://apiraiser.com
repository: https://github.com/horizech/apiraiser_dart

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter_secure_storage: ^6.0.0
  http: ^0.13.5
  #equatable: ^2.0.5
  #json_annotation: ^4.7.0
  
  
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
