name: apiraiser
description: Dart package for accessing Apiraiser, a headless CMS which provides easy-to-use backend for various kinds of applications like E-commerce, blogs, CMS etc.
version: 1.0.1
homepage: https://apiraiser.com
repository: https://github.com/horizech/apiraiser_dart
#publish_to: "none"

environment:
  sdk: ">=2.18.1 <4.0.0"

dependencies:
  flutter_secure_storage: ^9.0.0
  dio: ^5.3.3
  jwt_decoder: ^2.0.1
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
