name: apiraiser
description: Dart package for accessing Apiraiser, a headless CMS which provides easy-to-use backend for various kinds of applications like E-commerce, blogs, CMS etc.
version: 0.2.3
homepage: https://API/v1raiser.com
repository: https://github.com/horizech/API/v1raiser_dart
#publish_to: "none"

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  dio: ^5.3.3
  jwt_decoder: ^2.0.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
